---
- name: Install nginx repo key
  apt_key: 
    url: http://nginx.org/keys/nginx_signing.key
    state: present

- name: Install nginx repo
  apt_repository:
    repo: 'deb http://nginx.org/packages/ubuntu/ {{ ansible_distribution_release }} nginx'
    state: present
    update_cache: yes

- name: Install nginx packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ nginx_packages }}"
